runtime: custom
env: flex

network:
  session_affinity: true

manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10

env_variables:
  DRL_LUNAR_JOBS_ROOT: /tmp/drl_lunar_jobs
  DRL_LUNAR_MAX_WORKERS: "1"

service_account: administrator@deeprl-031026.iam.gserviceaccount.com
